name: numberpicker
version: 2.0.1
description: NumberPicker is a widget allowing user to choose numbers by scrolling spinners.
homepage: https://github.com/MarcinusX/NumberPicker

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true

dev_dependencies:
  flutter_test:
    sdk: flutter